#การรับข้อมูลทางเเป้นพิมพ์ด้วย Python
name = input('ป้อนชื่อ : ')
yearBorn = input('ป้อนปีเกิด : ')
print('-----------------------------------')
#ฟังก์ชั่นในการเเปลงข้อมูลจากข้อความเปนตัวเลข int( ), folat( )
#ฟังก์ชั่นในการเเปลงข้อมูลจากตัวเลขเป็นข้อความ str( )
print(f'ยินดีต้อนรับ {name} เกิดปี {yearBorn} อายุ {2023 - int(yearBorn)}') 
print('ยินดีต้อนรับ',name,'เกิดปี',yearBorn,'อายุ',2023-int(yearBorn))
print('ยินดีต้อนรับ'+name+'เกิดปี'+yearBorn+'อายุ'+2023-str(yearBorn))
print('ยินดีต้อนรับ {} เกิดปี {} อายุ {} '.format(name,yearBorn,2023-int(yearBorn)))
print('ยินดีต้อนรับ %s เกิดปี %s อายุ %d ' %(name,yearBorn,2023-int(yearBorn)))